### ISSUE TITLE
Extension (Julia 1.9)

### ISSUE THREAD

**Issue by DominiqueMakowski** [itsdfish/SSMPlots.jl#5]
Just watched the talk about 1.9 and the new dependency system of extensions. Could this be used as such so that when say SSM and StatsPlots are loaded then this gets loaded too?

**Comment by itsdfish** [comment]
@DominiqueMakowski, i tried package extensions as my [first approach](https://github.com/itsdfish/SequentialSamplingModels.jl/issues/35#issuecomment-1636731005), but I found it to be very limiting and not very useful. From a user perspective, I don't there is much of a difference aside from typing `using StatsPlots` vs. `using SSMPlots`.

**Comment by itsdfish** [comment]
Hopefully, they make the feature easier to use and more flexible in the future.

**Comment by DominiqueMakowski** [comment]
>  I don't there is much of a difference aside from typing using StatsPlots vs. using SSMPlots

Personally, I can imagine that users will have some plotting package loaded in their setup anyways. Whereas adding another package makes the (already) long list longer (and another thing to think about). 

<sub>*Note that this very likely comes from a place of personal bias, I am currently quite reserved regarding the tendency in Julia to atomize the ecosystem into tiny packages. I can see how it makes sense from a development perspective (especially at the beginning, but in the long run it can become a problem once the original maintainers do not have as much time to dedicate - speaking from personal experience 🥲), but from a user one it somehow really annoys me to for instance have to load the entire LinearAlgebra just to use `I*2` somewhere. But again, I'm new to Julia, so maybe there is some specific good reasons to have smaller bites* 🤷 </sub>

**Comment by itsdfish** [comment]
Yeah. I understand. Sometimes there are tradeoffs and judgment calls. The modular design is good for development because it makes everything composable. However, I'm not sure if the user experience is much better or worse in Python. If you want to use linear algebra, you will have to call `import numpy as np`. In some cases,  large packages have lots of nesting, which requires statements like `from scipy.module.submodule ...`.  From what I can tell, large nested libraries and smaller composable libraries would suffer similarly from developer neglect. 

I do like the idea of conditionally loading SSMPlots, but unfortunately the package extensions feature does not make that easy or even possible right now. I'll revisit the issue if package extensions becomes more flexible in the future.
